### ISSUE TITLE
HomeIndexMyElectives - Krach, pokud (StudentId is null)

### ISSUE THREAD

**Issue by Xopabyteh** [mensagymnazium/IntranetGen3#127]
Pokud uživatel není student (StudentId je null), jde do chyby:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Status(StatusCode="PermissionDenied", Detail="System.Security.SecurityException: currentUser.StudentId is not null
         at Havit.Diagnostics.Contracts.Contract.ThrowException[TException](String message)
         at MensaGymnazium.IntranetGen3.Facades.SubjectRegistrationProgressValidationFacade.GetProgressOfCurrentStudentAsync() in E:\repos\_MG\IntranetGen3\Facades\SubjectRegistrationProgressValidationFacade.cs:line 27
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at ProtoBuf.Grpc.Configuration.ServerExceptionsInterceptorBase.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in /_/src/protobuf-net.Grpc/Configuration/SimpleRpcExceptionsInterceptor.cs:line 69")
Grpc.Core.RpcException: Status(StatusCode="PermissionDenied", Detail="System.Security.SecurityException: currentUser.StudentId is not null
   at Havit.Diagnostics.Contracts.Contract.ThrowException[TException](String message)
   at MensaGymnazium.IntranetGen3.Facades.SubjectRegistrationProgressValidationFacade.GetProgressOfCurrentStudentAsync() in E:\repos\_MG\IntranetGen3\Facades\SubjectRegistrationProgressValidationFacade.cs:line 27
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
   at ProtoBuf.Grpc.Configuration.ServerExceptionsInterceptorBase.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in /_/src/protobuf-net.Grpc/Configuration/SimpleRpcExceptionsInterceptor.cs:line 69")
   at Havit.Blazor.Grpc.Client.WebAssembly.AuthorizationGrpcClientInterceptor.<HandleAsyncUnaryResponse>d__1`1[[MensaGymnazium.IntranetGen3.Contracts.StudentRegistrationProgressDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Havit.Blazor.Grpc.Client.Cancellation.CancellationWorkaroundGrpcClientInterceptor.<HandleResponseAsync>d__1`1[[MensaGymnazium.IntranetGen3.Contracts.StudentRegistrationProgressDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Havit.Blazor.Grpc.Client.ServerExceptions.ServerExceptionsGrpcClientInterceptor.<HandleResponseAsync>d__5`1[[MensaGymnazium.IntranetGen3.Contracts.StudentRegistrationProgressDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Havit.Blazor.Grpc.Client.ServerExceptions.ServerExceptionsGrpcClientInterceptor.<HandleResponseAsync>d__5`1[[MensaGymnazium.IntranetGen3.Contracts.StudentRegistrationProgressDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at ProtoBuf.Grpc.Internal.Reshape.<UnaryTaskAsyncImpl>d__16`2[[ProtoBuf.Grpc.Internal.Empty, protobuf-net.Grpc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67],[MensaGymnazium.IntranetGen3.Contracts.StudentRegistrationProgressDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 554
   at MensaGymnazium.IntranetGen3.Web.Client.Pages.Electives.HomeIndexMyElectives.OnAfterRenderAsync(Boolean firstRender) in E:\repos\_MG\IntranetGen3\Web.Client\Pages\Electives\HomeIndexMyElectives.razor.cs:line 19
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by hakenr** [comment]
(Děje se, pokud se přihlásím účtem, který není student.)

**Comment by Xopabyteh** [comment]
Fixnuto v #153
