### ISSUE TITLE
KeyNotFoundException  ze StudentsDataStore

### ISSUE THREAD

**Issue by hakenr** [mensagymnazium/IntranetGen3#98]
Z telemetrie Azure Application Insights (předvedu ve čtvrtek) se ukazuje tato chyba:

Evidentně nastává situace:
1. Student A není dosud intranetu znám (není v DB). Nepřihlásil se dosud.
2. Přichází student B, spustí intranet, načte se mu StudentsDataStore, kde student A zatím v datech není.
3. Mezi tím přijde student A, přihlásí se k intranetu, založí se mu záznam v DB, vytvoří si zápis na předmět.
4. Student B přichází na StudentSubjectRegistrationsGrid a chce si zobrazit seznam registrací. V datech ze serveru přichází ID studenta A, kterého však student B nemá v StudentsDataStore a padne to.

Nastává to docela často, pokusím se během dneška opravit. cc @MartinT1, @SvizelPritula, @VojtaT04, @zaqlp 

```
KeyNotFoundException: Arg_KeyNotFoundWithKey, 75
   at System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MensaGymnazium.IntranetGen3.Contracts.Security.StudentReferenceDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 )
   at Havit.Blazor.Components.Web.Services.DataStores.DictionaryStaticDataStore`2[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MensaGymnazium.IntranetGen3.Contracts.Security.StudentReferenceDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetByKey(Int32 key, Boolean throwIfNotLoaded)
   at MensaGymnazium.IntranetGen3.Web.Client.Pages.Electives.StudentSubjectRegistrationsGrid.<BuildRenderTree>b__50_4(StudentSubjectRegistrationDto i)
   at Havit.Blazor.Components.Web.Bootstrap.HxGridColumn`1[[MensaGymnazium.IntranetGen3.Contracts.StudentSubjectRegistrationDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetItemCellTemplate(StudentSubjectRegistrationDto item)
   at Havit.Blazor.Components.Web.Bootstrap.HxGridColumnBase`1[[MensaGymnazium.IntranetGen3.Contracts.StudentSubjectRegistrationDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Havit.Blazor.Components.Web.Bootstrap.IHxGridColumn<TItem>.GetItemCellTemplate(StudentSubjectRegistrationDto item)
   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.<>c__DisplayClass187_4[[MensaGymnazium.IntranetGen3.Contracts.StudentSubjectRegistrationDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__11(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 , RenderFragment )
   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.<>c__DisplayClass187_7[[MensaGymnazium.IntranetGen3.Contracts.StudentSubjectRegistrationDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__15(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1[[MensaGymnazium.IntranetGen3.Contracts.StudentSubjectRegistrationDto, MensaGymnazium.IntranetGen3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
```

**Comment by hakenr** [comment]
Je to nasazeno. Kdo má spuštěnou ještě verzi front-endu před nasazením, může se s chybou setkat. Kdo si načte/restartuje nový FE, už by vidět neměl.
